using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PewPew.Ecs.Hybrid.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class ArchetypeSourceGenerator : IIncrementalGenerator
{
    private const string ArchetypeAttributeFullName = "PewPew.Ecs.Hybrid.ArchetypeAttribute";

    private const string ArchetypeAttributeSource = @"// <auto-generated/>
#nullable enable
using System;

namespace PewPew.Ecs.Hybrid
{
    [AttributeUsage(AttributeTargets.Struct)]
    internal sealed class ArchetypeAttribute : Attribute
    {
        public Type? Mask { get; set; }
        public string? ArchetypeName { get; set; }
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject the [Archetype] attribute into every consuming project
        context.RegisterPostInitializationOutput(
            ctx => ctx.AddSource("PewPew.Ecs.Hybrid.ArchetypeAttribute.g.cs", ArchetypeAttributeSource));

        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is StructDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetArchetypeInfo(ctx))
            .Where(static x => x is not null)
            .Collect();

        context.RegisterSourceOutput(provider, (ctx, infos) =>
        {
            var allInfos = infos.OfType<ArchetypeInfo>().ToList();
            foreach (var info in allInfos)
                GenerateArchetype(ctx, info, allInfos);
        });
    }

    private static ArchetypeInfo? GetArchetypeInfo(GeneratorSyntaxContext context)
    {
        var structDecl = (StructDeclarationSyntax)context.Node;

        // Syntactic pre-filter: cheap string check to find candidates.
        // Full semantic verification is done inside TryAnalyze via structSymbol.GetAttributes().
        foreach (var attributeList in structDecl.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var name = attribute.Name.ToString();
                if (name == "Archetype" || name == "ArchetypeAttribute"
                    || name.EndsWith(".Archetype") || name.EndsWith(".ArchetypeAttribute"))
                {
                    return ArchetypeAnalyzer.TryAnalyze(structDecl, context.SemanticModel);
                }
            }
        }

        return null;
    }

    private static void GenerateArchetype(SourceProductionContext context, ArchetypeInfo info, IReadOnlyList<ArchetypeInfo> allInfos)
    {
        var code = new CodeGenerator().GenerateAllCode(info, allInfos);
        context.AddSource($"{info.ClassName}.Archetype.g.cs", code);
    }
}


