<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>11.0</LangVersion>
        <TargetFrameworks>netstandard2.1;net7.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PewPew.Ecs.Core\PewPew.Ecs.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    </ItemGroup>

    <Import Project="ProjectSettings.props" />

</Project>
