<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>11.0</LangVersion>
        <TargetFrameworks>netstandard2.1;net7.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>PewPew.Ecs.Filters</PackageId>
        <Authors>Eugene Levchenkov</Authors>
        <Title>PewPew.Ecs.Fitlers</Title>
        <Description>Filters for PewPew.Ecs library</Description>
        <PackageProjectUrl>https://github.com/Levchenkov/PewPew.Ecs</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/Levchenkov/PewPew.Ecs/blob/main/LICENSE</PackageLicenseUrl>
        <PackageTags>ecs sparse-set game-dev ecs-filters</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PewPew.Ecs.Core\PewPew.Ecs.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    </ItemGroup>

    <Import Project="ProjectSettings.props" />

</Project>
