<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>11.0</LangVersion>
        <TargetFrameworks>netstandard2.1;net7.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PewPew.Ecs.Core\PewPew.Ecs.Core.csproj" />
      <ProjectReference Include="..\PewPew.Ecs.Filters\PewPew.Ecs.Filters.csproj" />
    </ItemGroup>

    <Import Project="../PewPew.Ecs.Filters/ProjectSettings.props" />

    <ItemGroup>
        <ProjectReference Include="..\PewPew.Ecs.SourceGenerators\PewPew.Ecs.SourceGenerators.csproj" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
